-- =====================================================
-- Dawning Gateway - Database Initialization Script
-- Auto-synced from: apps/gateway/docs/sql/schema/
-- Generated at: 2025-12-30 12:52:40
-- 
-- DO NOT EDIT THIS FILE DIRECTLY!
-- Edit the source files in apps/gateway/docs/sql/schema/
-- Then run: deploy/scripts/sync-schema.ps1
-- =====================================================

-- =====================================================
-- Source: 001_users.sql
-- =====================================================
-- Create users table
CREATE TABLE IF NOT EXISTS `users` (
    `id` CHAR(36) NOT NULL COMMENT 'User unique identifier (GUID)',
    `username` VARCHAR(50) NOT NULL COMMENT 'Username (login name)',
    `password_hash` VARCHAR(255) NOT NULL COMMENT 'Password hash',
    `email` VARCHAR(100) NULL COMMENT 'Email',
    `phone_number` VARCHAR(20) NULL COMMENT 'Phone number',
    `display_name` VARCHAR(100) NULL COMMENT 'Display name',
    `avatar` VARCHAR(500) NULL COMMENT 'Avatar URL',
    `role` VARCHAR(50) NOT NULL DEFAULT 'user' COMMENT 'Role (admin, user, manager, etc.)',
    `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Is active',
    `is_system` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Is system user (system users cannot be deleted/disabled)',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Is deleted (soft delete)',
    `email_confirmed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Email confirmed',
    `phone_number_confirmed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Phone confirmed',
    `last_login_at` DATETIME NULL COMMENT 'Last login time',
    `failed_login_count` INT NOT NULL DEFAULT 0 COMMENT 'Failed login count',
    `lockout_end` DATETIME NULL COMMENT 'Lockout end time',
    `lockout_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Lockout enabled',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    `created_by` CHAR(36) NULL COMMENT 'Creator ID',
    `updated_by` CHAR(36) NULL COMMENT 'Updater ID',
    `remark` VARCHAR(500) NULL COMMENT 'Remark',
    `timestamp` BIGINT NOT NULL DEFAULT 0 COMMENT 'Timestamp in milliseconds (for pagination)',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_username` (`username` ASC),
    UNIQUE INDEX `uk_email` (`email` ASC),
    INDEX `idx_role` (`role` ASC),
    INDEX `idx_is_active` (`is_active` ASC),
    INDEX `idx_is_system` (`is_system` ASC),
    INDEX `idx_is_deleted` (`is_deleted` ASC),
    INDEX `idx_created_at` (`created_at` DESC),
    INDEX `idx_timestamp` (`timestamp` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Users table';

-- Insert initial admin user (password: Admin@123)
INSERT INTO `users` (
    `id`,
    `username`,
    `password_hash`,
    `email`,
    `display_name`,
    `role`,
    `is_active`,
    `is_system`,
    `timestamp`,
    `created_at`
) VALUES (
    UUID(),
    'admin',
    '100000;HQ2Qh1DuRQGvMRyDJxW23Q==;kgr3tG5/7WTyN/xjxDdWdhRJW740p0kwlcHKnFfIoMc=', -- PBKDF2 hash of 'Admin@123'
    'admin@dawning.com',
    'Administrator',
    'admin',
    1,
    1,
    UNIX_TIMESTAMP() * 1000,
    UTC_TIMESTAMP()
);

-- Insert test user (password: Admin@123)
INSERT INTO `users` (
    `id`,
    `username`,
    `password_hash`,
    `email`,
    `display_name`,
    `role`,
    `is_active`,
    `is_system`,
    `timestamp`,
    `created_at`
) VALUES (
    UUID(),
    'user',
    '100000;HQ2Qh1DuRQGvMRyDJxW23Q==;kgr3tG5/7WTyN/xjxDdWdhRJW740p0kwlcHKnFfIoMc=', -- PBKDF2 hash of 'Admin@123'
    'user@dawning.com',
    'Test User',
    'user',
    1,
    0,
    UNIX_TIMESTAMP() * 1000,
    UTC_TIMESTAMP()
);

-- =====================================================
-- Source: 002_claim_types_system_configs.sql
-- =====================================================
-- ====================================================
-- Create claim_types and system_configs Tables
-- Date: 2025-12-09 (Updated: 2025-12-19)
-- Description: Create claim types and system config tables
-- ====================================================

USE `dawning_identity`;

-- ====================================================
-- 1. Claim Types Table
-- ====================================================
DROP TABLE IF EXISTS `claim_types`;

CREATE TABLE `claim_types` (
    `id` CHAR(36) NOT NULL COMMENT 'Primary key (GUID)',
    `name` VARCHAR(200) NOT NULL COMMENT 'Name',
    `display_name` VARCHAR(200) NOT NULL COMMENT 'Display name',
    `type` VARCHAR(50) NOT NULL COMMENT 'Type (String, Int, DateTime, Boolean, Enum)',
    `description` VARCHAR(500) NULL COMMENT 'Description',
    `required` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Is required',
    `non_editable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'User editable (0=editable, 1=non-editable)',
    `timestamp` BIGINT NOT NULL COMMENT 'Unix timestamp in milliseconds (UTC, for indexing and pagination)',
    `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time (UTC)',
    `updated` DATETIME NULL COMMENT 'Updated time (UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_name` (`name`),
    INDEX `idx_type` (`type`),
    INDEX `idx_timestamp` (`timestamp`),
    INDEX `idx_created` (`created`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Claim types table';

-- ====================================================
-- 2. System Config Table
-- ====================================================
DROP TABLE IF EXISTS `system_configs`;

CREATE TABLE `system_configs` (
    `id` CHAR(36) NOT NULL COMMENT 'Primary key (GUID)',
    `name` VARCHAR(200) NOT NULL COMMENT 'Config group name',
    `key` VARCHAR(200) NOT NULL COMMENT 'Config key',
    `value` TEXT NULL COMMENT 'Config value',
    `description` VARCHAR(500) NULL COMMENT 'Description',
    `non_editable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Is read-only (0=editable, 1=non-editable)',
    `timestamp` BIGINT NOT NULL COMMENT 'Unix timestamp in milliseconds (UTC, for indexing and pagination)',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time (UTC)',
    `updated_at` DATETIME NULL COMMENT 'Updated time (UTC)',
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_key` (`key`),
    INDEX `idx_name_key` (`name`, `key`),
    INDEX `idx_timestamp` (`timestamp`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System config table';

-- ====================================================
-- 3. Insert Initial Data (Optional)
-- ====================================================

-- Insert basic claim types
INSERT INTO `claim_types` (`id`, `name`, `display_name`, `type`, `description`, `required`, `non_editable`, `timestamp`, `created`) VALUES
(UUID(), 'sub', 'Subject', 'String', 'User unique identifier', 1, 1, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'name', 'Name', 'String', 'User name', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'email', 'Email', 'String', 'Email address', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'email_verified', 'Email Verified', 'Boolean', 'Email confirmed', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'phone_number', 'Phone Number', 'String', 'Phone number', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'phone_number_verified', 'Phone Number Verified', 'Boolean', 'Phone number confirmed', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'role', 'Role', 'String', 'User role', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'birthdate', 'Birthdate', 'DateTime', 'Date of birth', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'gender', 'Gender', 'Enum', 'Gender', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'locale', 'Locale', 'String', 'Language locale', 0, 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW());

-- Insert system config examples
INSERT INTO `system_configs` (`id`, `name`, `key`, `value`, `description`, `non_editable`, `timestamp`, `created_at`) VALUES
(UUID(), 'System', 'Version', '1.0.0', 'System version number', 1, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'System', 'Environment', 'Development', 'System runtime environment', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Client', 'DefaultRedirectUri', 'http://localhost:5173/callback', 'Default redirect URI', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Client', 'DefaultLogoutUri', 'http://localhost:5173/', 'Default logout URI', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Token', 'AccessTokenLifetime', '3600', 'Access token lifetime (seconds)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Token', 'RefreshTokenLifetime', '86400', 'Refresh token lifetime (seconds)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW());

-- ====================================================
-- 4. Verify Table Creation
-- ====================================================
SELECT 
    TABLE_NAME AS 'Table Name',
    TABLE_ROWS AS 'Row Count',
    TABLE_COMMENT AS 'Comment'
FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = 'dawning_identity' 
AND TABLE_NAME IN ('claim_types', 'system_configs');

-- =====================================================
-- Source: 003_roles.sql
-- =====================================================
-- 005_create_roles_table.sql
-- Create roles table and initial data

-- Create roles table
CREATE TABLE IF NOT EXISTS `roles` (
  `id` CHAR(36) NOT NULL COMMENT 'Role ID (GUID)',
  `name` VARCHAR(50) NOT NULL COMMENT 'Role name (unique identifier, e.g., admin, user, manager)',
  `display_name` VARCHAR(100) NOT NULL COMMENT 'Role display name',
  `description` VARCHAR(500) DEFAULT NULL COMMENT 'Role description',
  `is_system` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Is system role (system roles cannot be deleted)',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Is active',
  `permissions` JSON DEFAULT NULL COMMENT 'Role permissions list (JSON array)',
  `timestamp` BIGINT NOT NULL DEFAULT 0 COMMENT 'Timestamp (millisecond Unix timestamp)',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `created_by` CHAR(36) DEFAULT NULL COMMENT 'Creator ID',
  `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  `updated_by` CHAR(36) DEFAULT NULL COMMENT 'Updater ID',
  `deleted_at` DATETIME DEFAULT NULL COMMENT 'Soft delete time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_roles_name` (`name`),
  KEY `idx_roles_is_active` (`is_active`),
  KEY `idx_roles_timestamp` (`timestamp`),
  KEY `idx_roles_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Roles table';

-- Insert system predefined roles
INSERT INTO `roles` (`id`, `name`, `display_name`, `description`, `is_system`, `is_active`, `permissions`, `created_at`) VALUES
(UUID(), 'super_admin', 'Super Administrator', 'System highest privilege role, has all permissions', 1, 1, 
 JSON_ARRAY('*:*:*'), NOW()),
 
(UUID(), 'admin', 'System Administrator', 'System administrator role, can manage users, roles, applications, etc.', 1, 1, 
 JSON_ARRAY(
   'user:*:*',
   'role:read:*',
   'application:*:*',
   'scope:*:*',
   'claim-type:*:*',
   'system-config:*:*'
 ), NOW()),
 
(UUID(), 'user_manager', 'User Manager', 'Responsible for user account management', 1, 1, 
 JSON_ARRAY(
   'user:read:*',
   'user:create:*',
   'user:update:*',
   'user:reset-password:*'
 ), NOW()),
 
(UUID(), 'auditor', 'Auditor', 'Read-only access, can view all data but cannot modify', 1, 1, 
 JSON_ARRAY(
   'user:read:*',
   'role:read:*',
   'application:read:*',
   'scope:read:*',
   'audit-log:read:*'
 ), NOW()),
 
(UUID(), 'user', 'User', 'Regular user role, can only manage own information', 1, 1, 
 JSON_ARRAY(
   'user:read:own',
   'user:update:own'
 ), NOW());

-- Display creation results
SELECT 'Roles table created successfully!' AS message;
SELECT id, name, display_name, description, is_system, is_active FROM roles;

-- =====================================================
-- Source: 004_user_roles.sql
-- =====================================================
-- 006_create_user_roles_table.sql
-- Create user-role association table

-- Create user roles association table
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` CHAR(36) NOT NULL COMMENT 'Association ID (GUID)',
  `user_id` CHAR(36) NOT NULL COMMENT 'User ID',
  `role_id` CHAR(36) NOT NULL COMMENT 'Role ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Assignment time',
  `created_by` CHAR(36) DEFAULT NULL COMMENT 'Assigner ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_roles` (`user_id`, `role_id`),
  KEY `idx_user_roles_user_id` (`user_id`),
  KEY `idx_user_roles_role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User roles association table';

-- Assign admin and super_admin roles to admin user
INSERT INTO `user_roles` (`id`, `user_id`, `role_id`, `created_at`)
SELECT 
  UUID() AS id,
  u.id AS user_id,
  r.id AS role_id,
  NOW() AS created_at
FROM `users` u
CROSS JOIN `roles` r
WHERE u.username = 'admin' 
  AND r.name IN ('admin', 'super_admin')
  AND r.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM `user_roles` ur 
    WHERE ur.user_id = u.id AND ur.role_id = r.id
  );

-- Assign user role to other test users
INSERT INTO `user_roles` (`id`, `user_id`, `role_id`, `created_at`)
SELECT 
  UUID() AS id,
  u.id AS user_id,
  r.id AS role_id,
  NOW() AS created_at
FROM `users` u
CROSS JOIN `roles` r
WHERE u.username IN ('zhangsan', 'lisi', 'wangwu', 'zhaoliu', 'sunqi')
  AND r.name = 'user'
  AND r.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM `user_roles` ur 
    WHERE ur.user_id = u.id AND ur.role_id = r.id
  );

-- Display creation results
SELECT 'User roles association table created successfully!' AS message;
SELECT 
  ur.id,
  u.username,
  r.name AS role_name,
  r.display_name AS role_display_name,
  ur.created_at
FROM user_roles ur
JOIN users u ON ur.user_id = u.id
JOIN roles r ON ur.role_id = r.id
ORDER BY u.username, r.name;

-- =====================================================
-- Source: 005_permissions.sql
-- =====================================================
-- ================================================
-- Create permissions table
-- File: 008_create_permissions_table.sql
-- Date: 2025-12-10
-- Description: Create permissions table for fine-grained access control
-- ================================================

-- Create permissions table
CREATE TABLE IF NOT EXISTS permissions (
    id CHAR(36) PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,           -- Permission code, format: resource:action (e.g., user:create, role:update)
    name VARCHAR(100) NOT NULL,                   -- Permission name
    description TEXT,                             -- Permission description
    resource VARCHAR(50) NOT NULL,                -- Resource type (user, role, audit-log, etc.)
    action VARCHAR(50) NOT NULL,                  -- Action type (create, read, update, delete, export, etc.)
    category VARCHAR(50),                         -- Permission category (administration, system, business, etc.)
    is_system TINYINT(1) DEFAULT 0,               -- Is system permission (cannot be deleted)
    is_active TINYINT(1) DEFAULT 1,               -- Is active
    display_order INT DEFAULT 0,                  -- Display order
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36),
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36),
    timestamp BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP() * 1000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create indexes
CREATE INDEX idx_permissions_code ON permissions(code);
CREATE INDEX idx_permissions_resource ON permissions(resource);
CREATE INDEX idx_permissions_category ON permissions(category);
CREATE INDEX idx_permissions_is_active ON permissions(is_active);

-- Create role permissions association table
CREATE TABLE IF NOT EXISTS role_permissions (
    id CHAR(36) PRIMARY KEY,
    role_id CHAR(36) NOT NULL,
    permission_id CHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36),
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create indexes
CREATE INDEX idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions(permission_id);

-- Insert system default permissions (using UUID())
INSERT INTO permissions (id, code, name, description, resource, action, category, is_system, display_order) VALUES
-- User management permissions
(UUID(), 'user:create', 'Create User', 'Allows creating new users', 'user', 'create', 'administration', 1, 100),
(UUID(), 'user:read', 'View User', 'Allows viewing user list and details', 'user', 'read', 'administration', 1, 101),
(UUID(), 'user:update', 'Update User', 'Allows updating user information', 'user', 'update', 'administration', 1, 102),
(UUID(), 'user:delete', 'Delete User', 'Allows deleting users', 'user', 'delete', 'administration', 1, 103),
(UUID(), 'user:export', 'Export User', 'Allows exporting user data', 'user', 'export', 'administration', 1, 104),
(UUID(), 'user:import', 'Import User', 'Allows importing user data', 'user', 'import', 'administration', 1, 105),
(UUID(), 'user:reset_password', 'Reset Password', 'Allows resetting user passwords', 'user', 'reset_password', 'administration', 1, 106),

-- Role management permissions
(UUID(), 'role:create', 'Create Role', 'Allows creating new roles', 'role', 'create', 'administration', 1, 200),
(UUID(), 'role:read', 'View Role', 'Allows viewing role list and details', 'role', 'read', 'administration', 1, 201),
(UUID(), 'role:update', 'Update Role', 'Allows updating role information', 'role', 'update', 'administration', 1, 202),
(UUID(), 'role:delete', 'Delete Role', 'Allows deleting roles', 'role', 'delete', 'administration', 1, 203),
(UUID(), 'role:assign_permissions', 'Assign Permissions', 'Allows assigning permissions to roles', 'role', 'assign_permissions', 'administration', 1, 204),

-- Permission management permissions
(UUID(), 'permission:create', 'Create Permission', 'Allows creating new permissions', 'permission', 'create', 'administration', 1, 300),
(UUID(), 'permission:read', 'View Permission', 'Allows viewing permission list and details', 'permission', 'read', 'administration', 1, 301),
(UUID(), 'permission:update', 'Update Permission', 'Allows updating permission information', 'permission', 'update', 'administration', 1, 302),
(UUID(), 'permission:delete', 'Delete Permission', 'Allows deleting permissions', 'permission', 'delete', 'administration', 1, 303),

-- Audit log permissions
(UUID(), 'audit-log:read', 'View Audit Logs', 'Allows viewing audit logs', 'audit-log', 'read', 'administration', 1, 400),
(UUID(), 'audit-log:export', 'Export Audit Logs', 'Allows exporting audit logs', 'audit-log', 'export', 'administration', 1, 401),
(UUID(), 'audit-log:cleanup', 'Cleanup Audit Logs', 'Allows cleaning up old audit logs', 'audit-log', 'cleanup', 'administration', 1, 402),

-- System config permissions (formerly system-metadata)
(UUID(), 'system-config:create', 'Create Config', 'Allows creating system config', 'system-config', 'create', 'administration', 1, 500),
(UUID(), 'system-config:read', 'View Config', 'Allows viewing system config', 'system-config', 'read', 'administration', 1, 501),
(UUID(), 'system-config:update', 'Update Config', 'Allows updating system config', 'system-config', 'update', 'administration', 1, 502),
(UUID(), 'system-config:delete', 'Delete Config', 'Allows deleting system config', 'system-config', 'delete', 'administration', 1, 503),

-- OpenIddict client permissions
(UUID(), 'client:create', 'Create Client', 'Allows creating OpenIddict clients', 'client', 'create', 'openiddict', 1, 600),
(UUID(), 'client:read', 'View Client', 'Allows viewing client list and details', 'client', 'read', 'openiddict', 1, 601),
(UUID(), 'client:update', 'Update Client', 'Allows updating client information', 'client', 'update', 'openiddict', 1, 602),
(UUID(), 'client:delete', 'Delete Client', 'Allows deleting clients', 'client', 'delete', 'openiddict', 1, 603),

-- System settings permissions
(UUID(), 'system:settings', 'System Settings', 'Allows modifying system settings', 'system', 'settings', 'system', 1, 700),
(UUID(), 'system:monitoring', 'System Monitoring', 'Allows viewing system monitoring information', 'system', 'monitoring', 'system', 1, 701),
(UUID(), 'system:logs', 'System Logs', 'Allows viewing system logs', 'system', 'logs', 'system', 1, 702);

-- Assign all permissions to admin role
INSERT INTO role_permissions (id, role_id, permission_id)
SELECT UUID(), r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'admin';

-- Assign basic read permissions to user role
INSERT INTO role_permissions (id, role_id, permission_id)
SELECT UUID(), r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'user'
AND p.code IN ('user:read', 'role:read', 'audit-log:read');

-- Assign audit-related permissions to auditor role
INSERT INTO role_permissions (id, role_id, permission_id)
SELECT UUID(), r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'auditor'
AND p.code IN ('audit-log:read', 'audit-log:export', 'user:read', 'role:read');

-- =====================================================
-- Source: 006_openiddict.sql
-- =====================================================
-- ====================================================
-- OpenIddict Tables for MySQL 8.0
-- Date: 2025-11-18
-- Description: OpenIddict core table structure
--   - timestamp: BIGINT millisecond Unix timestamp (UTC), for indexing and pagination
--   - created_at: DATETIME stores UTC time, set by application layer
-- ====================================================

-- 1. Applications Table
CREATE TABLE IF NOT EXISTS `openiddict_applications` (
    `id` CHAR(36) NOT NULL COMMENT 'Primary key (GUID)',
    `client_id` VARCHAR(100) NOT NULL COMMENT 'Client ID',
    `client_secret` VARCHAR(500) NULL COMMENT 'Client secret (hashed)',
    `display_name` VARCHAR(200) NULL COMMENT 'Display name',
    `type` VARCHAR(50) NULL COMMENT 'Client type (confidential, public)',
    `consent_type` VARCHAR(50) NULL COMMENT 'Consent type (explicit, implicit, systematic)',
    `permissions` TEXT NULL COMMENT 'Permissions list (JSON format)',
    `redirect_uris` TEXT NULL COMMENT 'Redirect URIs list (JSON format)',
    `post_logout_redirect_uris` TEXT NULL COMMENT 'Post-logout redirect URIs list (JSON format)',
    `requirements` TEXT NULL COMMENT 'Requirements list (JSON format)',
    `properties` TEXT NULL COMMENT 'Extended properties (JSON format)',
    `timestamp` BIGINT NOT NULL COMMENT 'Unix timestamp in milliseconds (UTC, for indexing and pagination)',
    `created_at` DATETIME NOT NULL COMMENT 'Created time (UTC)',
    `updated_at` DATETIME NULL COMMENT 'Updated time (UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_client_id` (`client_id`),
    INDEX `idx_type` (`type`),
    INDEX `idx_timestamp` (`timestamp`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OpenIddict applications table';

-- 2. Scopes Table
CREATE TABLE IF NOT EXISTS `openiddict_scopes` (
    `id` CHAR(36) NOT NULL COMMENT 'Primary key (GUID)',
    `name` VARCHAR(200) NOT NULL COMMENT 'Scope name',
    `display_name` VARCHAR(200) NULL COMMENT 'Display name',
    `description` VARCHAR(500) NULL COMMENT 'Description',
    `resources` TEXT NULL COMMENT 'Resources list (JSON format)',
    `properties` TEXT NULL COMMENT 'Extended properties (JSON format)',
    `timestamp` BIGINT NOT NULL COMMENT 'Unix timestamp in milliseconds (UTC, for indexing and pagination)',
    `created_at` DATETIME NOT NULL COMMENT 'Created time (UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_name` (`name`),
    INDEX `idx_timestamp` (`timestamp`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OpenIddict scopes table';

-- 3. Authorizations Table
CREATE TABLE IF NOT EXISTS `openiddict_authorizations` (
    `id` CHAR(36) NOT NULL COMMENT 'Primary key (GUID)',
    `application_id` CHAR(36) NULL COMMENT 'Associated application ID',
    `subject` VARCHAR(200) NULL COMMENT 'User identifier',
    `type` VARCHAR(50) NULL COMMENT 'Authorization type',
    `status` VARCHAR(50) NULL COMMENT 'Authorization status (valid, revoked)',
    `scopes` TEXT NULL COMMENT 'Authorized scopes list (JSON format)',
    `properties` TEXT NULL COMMENT 'Extended properties (JSON format)',
    `timestamp` BIGINT NOT NULL COMMENT 'Unix timestamp in milliseconds (UTC, for indexing and pagination)',
    `created_at` DATETIME NOT NULL COMMENT 'Created time (UTC)',
    PRIMARY KEY (`id`),
    INDEX `idx_application_id` (`application_id`),
    INDEX `idx_subject` (`subject`),
    INDEX `idx_status` (`status`),
    INDEX `idx_timestamp` (`timestamp`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OpenIddict authorizations table';

-- 4. Tokens Table
CREATE TABLE IF NOT EXISTS `openiddict_tokens` (
    `id` CHAR(36) NOT NULL COMMENT 'Primary key (GUID)',
    `application_id` CHAR(36) NULL COMMENT 'Associated application ID',
    `authorization_id` CHAR(36) NULL COMMENT 'Associated authorization ID',
    `subject` VARCHAR(200) NULL COMMENT 'User identifier',
    `type` VARCHAR(50) NULL COMMENT 'Token type (access_token, refresh_token, id_token)',
    `status` VARCHAR(50) NULL COMMENT 'Token status (valid, revoked, redeemed)',
    `payload` TEXT NULL COMMENT 'Token payload (JWT)',
    `reference_id` VARCHAR(200) NULL COMMENT 'Reference ID (for token introspection)',
    `expires_at` DATETIME NULL COMMENT 'Expiration time (UTC)',
    `timestamp` BIGINT NOT NULL COMMENT 'Unix timestamp in milliseconds (UTC, for indexing and pagination)',
    `created_at` DATETIME NOT NULL COMMENT 'Created time (UTC)',
    PRIMARY KEY (`id`),
    INDEX `idx_application_id` (`application_id`),
    INDEX `idx_authorization_id` (`authorization_id`),
    INDEX `idx_subject` (`subject`),
    INDEX `idx_reference_id` (`reference_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_expires_at` (`expires_at`),
    INDEX `idx_timestamp` (`timestamp`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OpenIddict tokens table';

-- =====================================================
-- Source: 007_api_identity_resources.sql
-- =====================================================
-- 011_create_api_identity_resources.sql
-- Purpose: Create API Resources and Identity Resources tables for OAuth2/OpenID Connect
-- Author: System
-- Date: 2025-12-10

-- ==================== API Resources Table ====================
-- API Resources represent protected APIs that can be accessed using tokens
CREATE TABLE IF NOT EXISTS `api_resources` (
    `id` CHAR(36) NOT NULL COMMENT 'API resource unique identifier',
    `name` VARCHAR(200) NOT NULL COMMENT 'API resource name (unique identifier)',
    `display_name` VARCHAR(200) NULL COMMENT 'Display name',
    `description` VARCHAR(500) NULL COMMENT 'Description',
    `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Is enabled',
    `allowed_access_token_signing_algorithms` TEXT NULL COMMENT 'Allowed access token signing algorithms (JSON array)',
    `show_in_discovery_document` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Show in discovery document',
    `properties` TEXT NULL COMMENT 'Extended properties (JSON object)',
    `timestamp` BIGINT NOT NULL COMMENT 'Timestamp',
    `created_at` DATETIME NOT NULL COMMENT 'Created time',
    `updated_at` DATETIME NULL COMMENT 'Updated time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_api_resources_name` (`name`),
    KEY `idx_api_resources_enabled` (`enabled`),
    KEY `idx_api_resources_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='API resources table';

-- ==================== API Resource Scopes Table ====================
-- Associates scopes with API resources
CREATE TABLE IF NOT EXISTS `api_resource_scopes` (
    `id` CHAR(36) NOT NULL COMMENT 'Unique identifier',
    `api_resource_id` CHAR(36) NOT NULL COMMENT 'API resource ID',
    `scope` VARCHAR(200) NOT NULL COMMENT 'Scope name',
    `created_at` DATETIME NOT NULL COMMENT 'Created time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_api_resource_scopes` (`api_resource_id`, `scope`),
    KEY `idx_api_resource_scopes_resource_id` (`api_resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='API resource scopes association table';

-- ==================== API Resource Claims Table ====================
-- Defines claims that should be included in access tokens for the API
CREATE TABLE IF NOT EXISTS `api_resource_claims` (
    `id` CHAR(36) NOT NULL COMMENT 'Unique identifier',
    `api_resource_id` CHAR(36) NOT NULL COMMENT 'API resource ID',
    `type` VARCHAR(200) NOT NULL COMMENT 'Claim type',
    `created_at` DATETIME NOT NULL COMMENT 'Created time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_api_resource_claims` (`api_resource_id`, `type`),
    KEY `idx_api_resource_claims_resource_id` (`api_resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='API resource claims table';

-- ==================== Identity Resources Table ====================
-- Identity Resources represent user identity information (OpenID Connect)
CREATE TABLE IF NOT EXISTS `identity_resources` (
    `id` CHAR(36) NOT NULL COMMENT 'Identity resource unique identifier',
    `name` VARCHAR(200) NOT NULL COMMENT 'Identity resource name (unique identifier)',
    `display_name` VARCHAR(200) NULL COMMENT 'Display name',
    `description` VARCHAR(500) NULL COMMENT 'Description',
    `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Is enabled',
    `required` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'User must consent',
    `emphasize` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Emphasize in consent screen',
    `show_in_discovery_document` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Show in discovery document',
    `properties` TEXT NULL COMMENT 'Extended properties (JSON object)',
    `timestamp` BIGINT NOT NULL COMMENT 'Timestamp',
    `created_at` DATETIME NOT NULL COMMENT 'Created time',
    `updated_at` DATETIME NULL COMMENT 'Updated time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_identity_resources_name` (`name`),
    KEY `idx_identity_resources_enabled` (`enabled`),
    KEY `idx_identity_resources_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Identity resources table';

-- ==================== Identity Resource Claims Table ====================
-- Defines claims that are associated with an identity resource
CREATE TABLE IF NOT EXISTS `identity_resource_claims` (
    `id` CHAR(36) NOT NULL COMMENT 'Unique identifier',
    `identity_resource_id` CHAR(36) NOT NULL COMMENT 'Identity resource ID',
    `type` VARCHAR(200) NOT NULL COMMENT 'Claim type',
    `created_at` DATETIME NOT NULL COMMENT 'Created time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_identity_resource_claims` (`identity_resource_id`, `type`),
    KEY `idx_identity_resource_claims_resource_id` (`identity_resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Identity resource claims table';

-- ==================== Verification ====================
-- Show created tables
SHOW TABLES LIKE '%resource%';

-- Show table structures
DESCRIBE api_resources;
DESCRIBE api_resource_scopes;
DESCRIBE api_resource_claims;
DESCRIBE identity_resources;
DESCRIBE identity_resource_claims;

-- =====================================================
-- Source: 008_system_logs.sql
-- =====================================================
-- Create system logs table
CREATE TABLE IF NOT EXISTS `system_logs` (
    `id` CHAR(36) NOT NULL COMMENT 'Log unique identifier (GUID)',
    `level` VARCHAR(20) NOT NULL COMMENT 'Log level (Info, Warning, Error)',
    `message` TEXT NOT NULL COMMENT 'Log message',
    `exception` TEXT NULL COMMENT 'Exception information (exception type and message)',
    `stack_trace` TEXT NULL COMMENT 'Exception stack trace',
    `source` VARCHAR(255) NULL COMMENT 'Exception source',
    `user_id` CHAR(36) NULL COMMENT 'Operating user ID',
    `username` VARCHAR(256) NULL COMMENT 'Operating username',
    `ip_address` VARCHAR(50) NULL COMMENT 'IP address',
    `user_agent` TEXT NULL COMMENT 'User agent',
    `request_path` VARCHAR(500) NULL COMMENT 'Request path',
    `request_method` VARCHAR(10) NULL COMMENT 'Request method (GET, POST, etc.)',
    `status_code` INT NULL COMMENT 'HTTP status code',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `timestamp` BIGINT NOT NULL COMMENT 'Timestamp (for sorting and query optimization)',
    PRIMARY KEY (`id`),
    INDEX `idx_level` (`level` ASC),
    INDEX `idx_created_at` (`created_at` DESC),
    INDEX `idx_timestamp` (`timestamp` DESC),
    INDEX `idx_user_id` (`user_id` ASC),
    INDEX `idx_username` (`username` ASC),
    INDEX `idx_level_created` (`level`, `created_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System logs table (application logs and exceptions)';

-- Create monthly partitions (example: January-December 2025)
-- Note: Use when database supports partitioning
-- ALTER TABLE `system_logs` PARTITION BY RANGE (YEAR(created_at) * 100 + MONTH(created_at)) (
--     PARTITION p202501 VALUES LESS THAN (202502),
--     PARTITION p202502 VALUES LESS THAN (202503),
--     PARTITION p202503 VALUES LESS THAN (202504),
--     PARTITION p202504 VALUES LESS THAN (202505),
--     PARTITION p202505 VALUES LESS THAN (202506),
--     PARTITION p202506 VALUES LESS THAN (202507),
--     PARTITION p202507 VALUES LESS THAN (202508),
--     PARTITION p202508 VALUES LESS THAN (202509),
--     PARTITION p202509 VALUES LESS THAN (202510),
--     PARTITION p202510 VALUES LESS THAN (202511),
--     PARTITION p202511 VALUES LESS THAN (202512),
--     PARTITION p202512 VALUES LESS THAN (202513),
--     PARTITION p_future VALUES LESS THAN MAXVALUE
-- );

-- =====================================================
-- Source: 009_audit_logs.sql
-- =====================================================
-- 007_create_audit_logs_table.sql
-- Create audit logs table

-- Create audit logs table
CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` CHAR(36) NOT NULL COMMENT 'Audit log ID (GUID)',
  `user_id` CHAR(36) DEFAULT NULL COMMENT 'Operating user ID',
  `username` VARCHAR(100) DEFAULT NULL COMMENT 'Operating username',
  `action` VARCHAR(100) NOT NULL COMMENT 'Action type (Create, Update, Delete, Login, Logout, etc.)',
  `entity_type` VARCHAR(100) DEFAULT NULL COMMENT 'Entity type (User, Role, Application, etc.)',
  `entity_id` CHAR(36) DEFAULT NULL COMMENT 'Entity ID',
  `description` VARCHAR(500) DEFAULT NULL COMMENT 'Action description',
  `ip_address` VARCHAR(45) DEFAULT NULL COMMENT 'IP address (supports IPv6)',
  `user_agent` VARCHAR(500) DEFAULT NULL COMMENT 'User agent',
  `request_path` VARCHAR(500) DEFAULT NULL COMMENT 'Request path',
  `request_method` VARCHAR(10) DEFAULT NULL COMMENT 'Request method (GET, POST, PUT, DELETE, etc.)',
  `status_code` INT DEFAULT NULL COMMENT 'HTTP status code',
  `old_values` JSON DEFAULT NULL COMMENT 'Values before modification (JSON)',
  `new_values` JSON DEFAULT NULL COMMENT 'Values after modification (JSON)',
  `timestamp` BIGINT NOT NULL COMMENT 'Timestamp (millisecond Unix timestamp)',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_user_id` (`user_id`),
  KEY `idx_audit_logs_action` (`action`),
  KEY `idx_audit_logs_entity_type` (`entity_type`),
  KEY `idx_audit_logs_entity_id` (`entity_id`),
  KEY `idx_audit_logs_created_at` (`created_at`),
  KEY `idx_audit_logs_timestamp` (`timestamp`),
  KEY `idx_audit_logs_ip_address` (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Audit logs table';

-- Display creation results
SELECT 'Audit logs table created successfully!' AS message;
SELECT COUNT(*) AS total_records FROM audit_logs;

-- =====================================================
-- Source: 010_gateway.sql
-- =====================================================
-- ============================================
-- Gateway Route and Cluster Management Tables (MySQL 8.0+)
-- ============================================

-- Gateway clusters table (must be created first since routes table references clusters)
CREATE TABLE IF NOT EXISTS gateway_clusters (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    cluster_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    load_balancing_policy VARCHAR(50) DEFAULT 'RoundRobin',
    destinations JSON NOT NULL,
    health_check_enabled TINYINT(1) DEFAULT 0,
    health_check_interval INT,
    health_check_timeout INT,
    health_check_path VARCHAR(200),
    passive_health_policy VARCHAR(50),
    session_affinity_enabled TINYINT(1) DEFAULT 0,
    session_affinity_policy VARCHAR(50),
    session_affinity_key_name VARCHAR(100),
    max_connections_per_server INT,
    request_timeout_seconds INT,
    allowed_http_versions VARCHAR(50),
    dangerous_accept_any_server_certificate TINYINT(1) DEFAULT 0,
    metadata JSON,
    is_enabled TINYINT(1) DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gateway cluster configuration table';

-- Gateway routes table
CREATE TABLE IF NOT EXISTS gateway_routes (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    route_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    cluster_id VARCHAR(100) NOT NULL,
    match_path VARCHAR(500) NOT NULL,
    match_methods VARCHAR(200),
    match_hosts TEXT,
    match_headers JSON,
    match_query_parameters JSON,
    transform_path_prefix VARCHAR(200),
    transform_path_remove_prefix VARCHAR(200),
    transform_request_headers JSON,
    transform_response_headers JSON,
    authorization_policy VARCHAR(100),
    rate_limiter_policy VARCHAR(100),
    cors_policy VARCHAR(100),
    timeout_seconds INT,
    sort_order INT DEFAULT 0,
    is_enabled TINYINT(1) DEFAULT 1,
    metadata JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gateway route configuration table';

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_gateway_routes_cluster_id ON gateway_routes(cluster_id);
CREATE INDEX IF NOT EXISTS idx_gateway_routes_is_enabled ON gateway_routes(is_enabled);
CREATE INDEX IF NOT EXISTS idx_gateway_routes_sort_order ON gateway_routes(sort_order);
CREATE INDEX IF NOT EXISTS idx_gateway_clusters_is_enabled ON gateway_clusters(is_enabled);

-- Insert default gateway cluster (Identity Service)
INSERT INTO gateway_clusters (cluster_id, name, description, destinations, load_balancing_policy, health_check_enabled, health_check_path, is_enabled)
VALUES 
('identity-cluster', 'Identity Service', 'Identity authentication service cluster', '{"destination1": {"Address": "http://localhost:5202"}}', 'RoundRobin', 1, '/health', 1)
ON DUPLICATE KEY UPDATE name=VALUES(name), destinations=VALUES(destinations);

-- Insert default gateway route
INSERT INTO gateway_routes (route_id, name, cluster_id, match_path, transform_path_remove_prefix, sort_order, is_enabled)
VALUES 
('identity-route', 'Identity API Route', 'identity-cluster', '/api/identity/{**catch-all}', '/api/identity', 0, 1)
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- =====================================================
-- Source: 011_rate_limit.sql
-- =====================================================
-- =============================================
-- Rate Limit Policies and IP Access Rules Tables
-- =============================================

-- Rate limit policies table
CREATE TABLE IF NOT EXISTS `rate_limit_policies` (
    `id` CHAR(36) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `display_name` VARCHAR(200),
    `policy_type` VARCHAR(50) NOT NULL DEFAULT 'fixed-window',
    `permit_limit` INT NOT NULL DEFAULT 100,
    `window_seconds` INT NOT NULL DEFAULT 60,
    `segments_per_window` INT NOT NULL DEFAULT 6,
    `queue_limit` INT NOT NULL DEFAULT 0,
    `tokens_per_period` INT NOT NULL DEFAULT 10,
    `replenishment_period_seconds` INT NOT NULL DEFAULT 1,
    `is_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `description` TEXT,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_rate_limit_policy_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- IP access rules table
CREATE TABLE IF NOT EXISTS `ip_access_rules` (
    `id` CHAR(36) NOT NULL,
    `ip_address` VARCHAR(50) NOT NULL,
    `rule_type` VARCHAR(20) NOT NULL DEFAULT 'blacklist',
    `description` TEXT,
    `is_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `expires_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME,
    `created_by` VARCHAR(100),
    PRIMARY KEY (`id`),
    KEY `idx_ip_access_rule_type` (`rule_type`),
    KEY `idx_ip_access_enabled` (`is_enabled`),
    KEY `idx_ip_access_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default rate limit policies
INSERT INTO `rate_limit_policies` (`id`, `name`, `display_name`, `policy_type`, `permit_limit`, `window_seconds`, `description`) VALUES
(UUID(), 'default', 'Default Policy', 'fixed-window', 100, 60, '100 requests per minute'),
(UUID(), 'strict', 'Strict Limit', 'fixed-window', 30, 60, '30 requests per minute'),
(UUID(), 'relaxed', 'Relaxed Limit', 'fixed-window', 500, 60, '500 requests per minute'),
(UUID(), 'api-standard', 'API Standard', 'sliding-window', 100, 60, 'Sliding window, 100 requests per minute'),
(UUID(), 'burst-allow', 'Allow Burst', 'token-bucket', 100, 60, 'Token bucket, allows short-term burst requests');

-- =====================================================
-- Source: 012_alert_rules.sql
-- =====================================================
-- ============================================
-- V8: Alert Rules and Alert History Tables
-- Date: 2025-12-17
-- Description: Add alert rules management and alert history tracking
-- ============================================

-- Alert rules table
CREATE TABLE IF NOT EXISTS `alert_rules` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL COMMENT 'Rule name',
    `description` VARCHAR(500) NULL COMMENT 'Rule description',
    `metric_type` VARCHAR(50) NOT NULL COMMENT 'Metric type: cpu, memory, response_time, error_rate, request_count',
    `operator` VARCHAR(20) NOT NULL COMMENT 'Comparison operator: gt, gte, lt, lte, eq',
    `threshold` DECIMAL(18,4) NOT NULL COMMENT 'Threshold value',
    `duration_seconds` INT NOT NULL DEFAULT 60 COMMENT 'Duration (seconds), alert triggers only after exceeding this time',
    `severity` VARCHAR(20) NOT NULL DEFAULT 'warning' COMMENT 'Severity level: info, warning, error, critical',
    `is_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether enabled',
    `notify_channels` VARCHAR(500) NULL COMMENT 'Notification channels, JSON array: ["email", "webhook"]',
    `notify_emails` VARCHAR(1000) NULL COMMENT 'Notification emails, comma-separated',
    `webhook_url` VARCHAR(500) NULL COMMENT 'Webhook URL',
    `cooldown_minutes` INT NOT NULL DEFAULT 5 COMMENT 'Cooldown time (minutes) to avoid duplicate alerts',
    `last_triggered_at` DATETIME NULL COMMENT 'Last triggered time',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_alert_rules_metric_type` (`metric_type`),
    INDEX `idx_alert_rules_is_enabled` (`is_enabled`),
    INDEX `idx_alert_rules_severity` (`severity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert rules table';

-- Alert history table
CREATE TABLE IF NOT EXISTS `alert_history` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `rule_id` BIGINT UNSIGNED NOT NULL COMMENT 'Alert rule ID',
    `rule_name` VARCHAR(100) NOT NULL COMMENT 'Rule name (denormalized)',
    `metric_type` VARCHAR(50) NOT NULL COMMENT 'Metric type',
    `metric_value` DECIMAL(18,4) NOT NULL COMMENT 'Metric value at trigger time',
    `threshold` DECIMAL(18,4) NOT NULL COMMENT 'Threshold value',
    `severity` VARCHAR(20) NOT NULL COMMENT 'Severity level',
    `message` VARCHAR(1000) NULL COMMENT 'Alert message',
    `status` VARCHAR(20) NOT NULL DEFAULT 'triggered' COMMENT 'Status: triggered, acknowledged, resolved',
    `triggered_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Trigger time',
    `acknowledged_at` DATETIME NULL COMMENT 'Acknowledgment time',
    `acknowledged_by` VARCHAR(100) NULL COMMENT 'Acknowledged by',
    `resolved_at` DATETIME NULL COMMENT 'Resolution time',
    `resolved_by` VARCHAR(100) NULL COMMENT 'Resolved by',
    `notify_sent` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether notification was sent',
    `notify_result` VARCHAR(500) NULL COMMENT 'Notification send result',
    INDEX `idx_alert_history_rule_id` (`rule_id`),
    INDEX `idx_alert_history_status` (`status`),
    INDEX `idx_alert_history_severity` (`severity`),
    INDEX `idx_alert_history_triggered_at` (`triggered_at`),
    CONSTRAINT `fk_alert_history_rule` FOREIGN KEY (`rule_id`) REFERENCES `alert_rules`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert history table';

-- Insert default alert rules
INSERT INTO `alert_rules` (`name`, `description`, `metric_type`, `operator`, `threshold`, `duration_seconds`, `severity`, `is_enabled`, `notify_channels`, `cooldown_minutes`) VALUES
('High CPU Usage', 'Alert when CPU usage exceeds 80%', 'cpu', 'gt', 80.0000, 60, 'warning', 1, '["email"]', 5),
('High Memory Usage', 'Alert when memory usage exceeds 85%', 'memory', 'gt', 85.0000, 60, 'warning', 1, '["email"]', 5),
('Critical Memory Usage', 'Alert when memory usage exceeds 95%', 'memory', 'gt', 95.0000, 30, 'critical', 1, '["email", "webhook"]', 5),
('High API Response Time', 'Alert when average response time exceeds 2000ms', 'response_time', 'gt', 2000.0000, 120, 'warning', 1, '["email"]', 10),
('High Error Rate', 'Alert when error rate exceeds 5%', 'error_rate', 'gt', 5.0000, 60, 'error', 1, '["email", "webhook"]', 5);

-- Rollback script
-- DROP TABLE IF EXISTS `alert_history`;
-- DROP TABLE IF EXISTS `alert_rules`;

-- =====================================================
-- Source: 013_user_sessions.sql
-- =====================================================
-- =============================================
-- User Session Management - Database Migration Script
-- Version: V4_add_user_sessions.sql
-- Date: 2025-12-16
-- =============================================

-- Create user sessions table
CREATE TABLE IF NOT EXISTS `user_sessions` (
    `id` CHAR(36) NOT NULL COMMENT 'Session ID',
    `user_id` CHAR(36) NOT NULL COMMENT 'User ID',
    `token_id` CHAR(36) NOT NULL COMMENT 'Associated token ID',
    `device_id` VARCHAR(64) NOT NULL COMMENT 'Device identifier',
    `device_type` VARCHAR(32) NOT NULL DEFAULT 'web' COMMENT 'Device type (web, mobile, desktop)',
    `device_name` VARCHAR(256) NULL COMMENT 'Device name/user agent',
    `ip_address` VARCHAR(45) NULL COMMENT 'IP address (supports IPv6)',
    `login_time` DATETIME NOT NULL COMMENT 'Login time',
    `last_active_time` DATETIME NOT NULL COMMENT 'Last active time',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_user_sessions_user_id` (`user_id`),
    INDEX `idx_user_sessions_device_id` (`user_id`, `device_id`),
    INDEX `idx_user_sessions_token_id` (`token_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User sessions table';

-- =============================================
-- Login Policy Configuration - Add to system configs table
-- =============================================

INSERT INTO `system_configs` (`id`, `name`, `key`, `value`, `description`, `non_editable`, `timestamp`, `created_at`) VALUES
(UUID(), 'Security', 'AllowMultipleDevices', 'true', 'Whether to allow multiple devices to login simultaneously', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Security', 'MaxDevices', '5', 'Maximum allowed devices (0 means unlimited)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Security', 'NewDevicePolicy', 'allow', 'New device login policy (allow/deny/kick_oldest)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Security', 'RefreshTokenLifetimeDays', '30', 'Refresh token lifetime (days)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()),
(UUID(), 'Security', 'AccessTokenLifetimeMinutes', '60', 'Access token lifetime (minutes)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW())
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- =============================================
-- Rollback script (execute manually if rollback is needed)
-- =============================================
-- DROP TABLE IF EXISTS `user_sessions`;
-- DELETE FROM `system_configs` WHERE `key` IN ('AllowMultipleDevices', 'MaxDevices', 'NewDevicePolicy', 'RefreshTokenLifetimeDays', 'AccessTokenLifetimeMinutes');

-- =====================================================
-- Source: 014_request_logs.sql
-- =====================================================
-- =====================================================
-- V5_add_request_logs.sql
-- Request Logs Table Creation Script
-- Created: 2025-12-16
-- Description: Store API request logs for monitoring and auditing
-- =====================================================

-- Request logs table
CREATE TABLE IF NOT EXISTS request_logs (
    id CHAR(36) NOT NULL PRIMARY KEY,
    request_id VARCHAR(100) NULL,
    method VARCHAR(10) NOT NULL,
    path VARCHAR(2048) NOT NULL,
    query_string VARCHAR(2048) NULL,
    status_code INT NOT NULL,
    response_time_ms BIGINT NOT NULL,
    client_ip VARCHAR(45) NULL,
    user_agent VARCHAR(1024) NULL,
    user_id CHAR(36) NULL,
    user_name VARCHAR(256) NULL,
    request_time DATETIME NOT NULL,
    request_body_size BIGINT NULL,
    response_body_size BIGINT NULL,
    exception TEXT NULL,
    additional_info JSON NULL,
    
    -- Indexes
    INDEX idx_request_logs_request_time (request_time),
    INDEX idx_request_logs_status_code (status_code),
    INDEX idx_request_logs_user_id (user_id),
    INDEX idx_request_logs_client_ip (client_ip),
    INDEX idx_request_logs_path (path(255)),
    INDEX idx_request_logs_method (method),
    
    -- Composite indexes for common queries
    INDEX idx_request_logs_time_status (request_time, status_code),
    INDEX idx_request_logs_time_path (request_time, path(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add table comment
ALTER TABLE request_logs COMMENT = 'API request logs table';

-- =====================================================
-- Log Retention Policy Configuration
-- =====================================================

-- Add log retention days configuration
INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Logging', 'RequestLogRetentionDays', '30', 'Request log retention days', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Logging' AND `key` = 'RequestLogRetentionDays'
);

-- Add slow request threshold configuration
INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Logging', 'SlowRequestThresholdMs', '1000', 'Slow request threshold (milliseconds)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Logging' AND `key` = 'SlowRequestThresholdMs'
);

-- Add request logging enabled configuration
INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Logging', 'RequestLoggingEnabled', 'true', 'Whether to enable request logging', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Logging' AND `key` = 'RequestLoggingEnabled'
);

-- =====================================================
-- Scheduled Cleanup Event (Optional, requires MySQL event scheduler)
-- =====================================================

-- Enable event scheduler (if not already enabled)
-- SET GLOBAL event_scheduler = ON;

-- Create log cleanup event (runs daily at 3:00 AM)
-- DELIMITER //
-- CREATE EVENT IF NOT EXISTS cleanup_request_logs
-- ON SCHEDULE EVERY 1 DAY
-- STARTS TIMESTAMP(CURRENT_DATE + INTERVAL 1 DAY, '03:00:00')
-- DO
-- BEGIN
--     DECLARE retention_days INT DEFAULT 30;
--     
--     -- Get retention days from config table
--     SELECT CAST(value AS UNSIGNED) INTO retention_days
--     FROM system_configs 
--     WHERE name = 'Logging' AND `key` = 'RequestLogRetentionDays'
--     LIMIT 1;
--     
--     -- Delete expired logs
--     DELETE FROM request_logs 
--     WHERE request_time < DATE_SUB(NOW(), INTERVAL retention_days DAY);
-- END //
-- DELIMITER ;

-- =====================================================
-- Verification
-- =====================================================

-- Show table structure
DESCRIBE request_logs;

-- Show configuration
SELECT * FROM system_configs WHERE name = 'Logging';

-- =====================================================
-- Source: 015_backup_records.sql
-- =====================================================
-- =====================================================
-- V6_add_backup_records.sql
-- Database Backup Records Table Creation Script
-- Created: 2025-12-16
-- Description: Store database backup history records
-- =====================================================

-- Backup records table
CREATE TABLE IF NOT EXISTS backup_records (
    id CHAR(36) NOT NULL PRIMARY KEY,
    file_name VARCHAR(512) NOT NULL,
    file_path VARCHAR(1024) NOT NULL,
    file_size_bytes BIGINT NOT NULL DEFAULT 0,
    backup_type VARCHAR(50) NOT NULL DEFAULT 'full',
    created_at DATETIME NOT NULL,
    description VARCHAR(500) NULL,
    is_manual BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    error_message TEXT NULL,
    
    -- Indexes
    INDEX idx_backup_records_created_at (created_at),
    INDEX idx_backup_records_status (status),
    INDEX idx_backup_records_type (backup_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add table comment
ALTER TABLE backup_records COMMENT = 'Database backup records table';

-- =====================================================
-- Backup Configuration Items
-- =====================================================

-- Add backup configuration to system configs table
INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'AutoBackupEnabled', 'true', 'Whether to enable automatic backup', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'AutoBackupEnabled'
);

INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'AutoBackupIntervalHours', '24', 'Automatic backup interval (hours)', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'AutoBackupIntervalHours'
);

INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'RetentionDays', '30', 'Backup retention days', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'RetentionDays'
);

INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'MaxBackupCount', '50', 'Maximum backup count', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'MaxBackupCount'
);

INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'BackupPath', 'backups', 'Backup storage path', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'BackupPath'
);

INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'CompressBackups', 'true', 'Whether to compress backup files', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'CompressBackups'
);
);

INSERT INTO system_configs (id, name, `key`, value, description, non_editable, timestamp, created_at)
SELECT UUID(), 'Backup', 'AutoBackupIncludeLogs', 'false', 'Whether automatic backup includes log tables', 0, UNIX_TIMESTAMP(NOW(3)) * 1000, NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM system_configs 
    WHERE name = 'Backup' AND `key` = 'AutoBackupIncludeLogs'
);

-- =====================================================
-- Verification
-- =====================================================

-- Show table structure
DESCRIBE backup_records;

-- Show configuration
SELECT * FROM system_configs WHERE name = 'Backup';

-- =====================================================
-- Source: 016_multitenancy.sql
-- =====================================================
-- ============================================
-- V8: Multi-tenancy Support
-- Created: 2025-12-23
-- Description: Add multi-tenancy support, including tenant table and tenant_id field for existing tables
-- ============================================

-- 1. Create tenants table
CREATE TABLE IF NOT EXISTS `tenants` (
    `id` CHAR(36) NOT NULL COMMENT 'Tenant ID',
    `code` VARCHAR(50) NOT NULL COMMENT 'Tenant code (unique identifier)',
    `name` VARCHAR(100) NOT NULL COMMENT 'Tenant name',
    `description` VARCHAR(500) NULL COMMENT 'Tenant description',
    `domain` VARCHAR(255) NULL COMMENT 'Bound domain',
    `email` VARCHAR(255) NULL COMMENT 'Contact email',
    `phone` VARCHAR(50) NULL COMMENT 'Contact phone',
    `logo_url` VARCHAR(500) NULL COMMENT 'Tenant logo URL',
    `settings` JSON NULL COMMENT 'Tenant settings (JSON format)',
    `connection_string` VARCHAR(500) NULL COMMENT 'Separate database connection string',
    `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Is active',
    `plan` VARCHAR(50) NOT NULL DEFAULT 'free' COMMENT 'Subscription plan',
    `subscription_expires_at` DATETIME NULL COMMENT 'Subscription expiration time',
    `max_users` INT NULL COMMENT 'Maximum users limit',
    `max_storage_mb` INT NULL COMMENT 'Maximum storage (MB)',
    `timestamp` BIGINT NOT NULL DEFAULT 0 COMMENT 'Timestamp (millisecond Unix timestamp)',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    `created_by` CHAR(36) NULL COMMENT 'Creator ID',
    `updated_by` CHAR(36) NULL COMMENT 'Updater ID',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenants_code` (`code`),
    UNIQUE KEY `uk_tenants_domain` (`domain`),
    KEY `idx_tenants_is_active` (`is_active`),
    KEY `idx_tenants_plan` (`plan`),
    KEY `idx_tenants_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tenants table';

-- 2. Add tenant_id field to existing tables (optional, enable as needed)
-- Note: Following operations may take a long time, please execute during maintenance window

-- 2.1 Users table
ALTER TABLE `users` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_users_tenant_id` (`tenant_id`);

-- 2.2 Roles table
ALTER TABLE `roles` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_roles_tenant_id` (`tenant_id`);

-- 2.3 Permissions table
ALTER TABLE `permissions` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_permissions_tenant_id` (`tenant_id`);

-- 2.4 System configs table
ALTER TABLE `system_configs` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_system_configs_tenant_id` (`tenant_id`);

-- 2.5 Audit logs table
ALTER TABLE `audit_logs` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_audit_logs_tenant_id` (`tenant_id`);

-- 2.6 System logs table
ALTER TABLE `system_logs` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_system_logs_tenant_id` (`tenant_id`);

-- 2.7 Alert rules table
ALTER TABLE `alert_rules` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_alert_rules_tenant_id` (`tenant_id`);

-- 2.8 Alert history table
ALTER TABLE `alert_history` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_alert_history_tenant_id` (`tenant_id`);

-- 2.9 Request logs table
ALTER TABLE `request_logs` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_request_logs_tenant_id` (`tenant_id`);

-- 2.10 Gateway routes table
ALTER TABLE `gateway_routes` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_gateway_routes_tenant_id` (`tenant_id`);

-- 2.11 Gateway clusters table
ALTER TABLE `gateway_clusters` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_gateway_clusters_tenant_id` (`tenant_id`);

-- 2.12 Rate limit policies table
ALTER TABLE `rate_limit_policies` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_rate_limit_policies_tenant_id` (`tenant_id`);

-- 2.13 IP access rules table
ALTER TABLE `ip_access_rules` 
ADD COLUMN `tenant_id` CHAR(36) NULL COMMENT 'Tenant ID' AFTER `id`,
ADD INDEX `idx_ip_access_rules_tenant_id` (`tenant_id`);

-- 3. Create default tenant (primary tenant)
INSERT INTO `tenants` (`id`, `code`, `name`, `description`, `is_active`, `plan`, `created_at`)
VALUES (
    UUID(),
    'default',
    'Default Tenant',
    'System default tenant for host administrators and public data',
    1,
    'enterprise',
    NOW()
);

-- 4. Associate existing data to default tenant (optional)
-- Uncomment the following statements to migrate existing data to default tenant
-- SET @default_tenant_id = (SELECT id FROM tenants WHERE code = 'default');
-- UPDATE users SET tenant_id = @default_tenant_id WHERE tenant_id IS NULL;
-- UPDATE roles SET tenant_id = @default_tenant_id WHERE tenant_id IS NULL;
-- UPDATE permissions SET tenant_id = @default_tenant_id WHERE tenant_id IS NULL;
-- ... similar for other tables

-- 5. Add tenant-related permissions
INSERT INTO `permissions` (`id`, `code`, `name`, `description`, `resource`, `action`, `category`, `is_active`, `sort_order`)
VALUES 
    (UUID(), 'tenant:create', 'Create Tenant', 'Allows creating new tenants', 'tenant', 'create', 'multitenancy', 1, 700),
    (UUID(), 'tenant:read', 'View Tenant', 'Allows viewing tenant list and details', 'tenant', 'read', 'multitenancy', 1, 701),
    (UUID(), 'tenant:update', 'Update Tenant', 'Allows updating tenant information', 'tenant', 'update', 'multitenancy', 1, 702),
    (UUID(), 'tenant:delete', 'Delete Tenant', 'Allows deleting tenants', 'tenant', 'delete', 'multitenancy', 1, 703),
    (UUID(), 'tenant:switch', 'Switch Tenant', 'Allows switching between tenants', 'tenant', 'switch', 'multitenancy', 1, 704);

-- ============================================
-- Rollback script (execute these statements if rollback needed)
-- ============================================
-- DROP TABLE IF EXISTS `tenants`;
-- ALTER TABLE `users` DROP COLUMN `tenant_id`, DROP INDEX `idx_users_tenant_id`;
-- ALTER TABLE `roles` DROP COLUMN `tenant_id`, DROP INDEX `idx_roles_tenant_id`;
-- ALTER TABLE `permissions` DROP COLUMN `tenant_id`, DROP INDEX `idx_permissions_tenant_id`;
-- ALTER TABLE `system_configs` DROP COLUMN `tenant_id`, DROP INDEX `idx_system_configs_tenant_id`;
-- ALTER TABLE `audit_logs` DROP COLUMN `tenant_id`, DROP INDEX `idx_audit_logs_tenant_id`;
-- ALTER TABLE `system_logs` DROP COLUMN `tenant_id`, DROP INDEX `idx_system_logs_tenant_id`;
-- ALTER TABLE `alert_rules` DROP COLUMN `tenant_id`, DROP INDEX `idx_alert_rules_tenant_id`;
-- ALTER TABLE `alert_history` DROP COLUMN `tenant_id`, DROP INDEX `idx_alert_history_tenant_id`;
-- ALTER TABLE `request_logs` DROP COLUMN `tenant_id`, DROP INDEX `idx_request_logs_tenant_id`;
-- ALTER TABLE `gateway_routes` DROP COLUMN `tenant_id`, DROP INDEX `idx_gateway_routes_tenant_id`;
-- ALTER TABLE `gateway_clusters` DROP COLUMN `tenant_id`, DROP INDEX `idx_gateway_clusters_tenant_id`;
-- ALTER TABLE `rate_limit_policies` DROP COLUMN `tenant_id`, DROP INDEX `idx_rate_limit_policies_tenant_id`;
-- ALTER TABLE `ip_access_rules` DROP COLUMN `tenant_id`, DROP INDEX `idx_ip_access_rules_tenant_id`;
-- DELETE FROM `permissions` WHERE `category` = 'multitenancy';

