using System.Data;
using Dapper;
using FirebirdSql.Data.FirebirdClient;

namespace Dawning.ORM.Dapper.Tests;

/// <summary>
/// Runs the full <see cref="OrmIntegrationTestBase"/> suite against a real
/// Firebird 4.0 database. Defaults to the local docker container provisioned
/// for ORM testing; override via the <c>DAWNING_ORM_FIREBIRD</c> env var.
///
/// Provisioning (one-time):
/// <code>
/// docker run -d --name dawning-orm-fb \
///   -e ISC_PASSWORD=fbtest -e FIREBIRD_DATABASE=ormtest.fdb \
///   -p 3050:3050 jacobalberty/firebird:v4
/// </code>
///
/// Firebird quirks that shape this suite:
/// - Identifiers are folded to UPPERCASE when unquoted; the FbAdapter emits
///   bare identifiers, so the schema is created without quoting and column
///   names like <c>Id</c>/<c>Name</c>/<c>Display</c> all resolve as their
///   uppercase equivalents.
/// - <c>TIMESTAMP</c> is reserved, so the shared <see cref="Widget.Timestamp"/>
///   property maps to a non-reserved <c>ts_ms</c> column instead.
/// - The <c>noOrder</c> table folds to <c>NOORDER</c>.
/// - <see cref="Guid"/> values bind to <c>CHAR(16) CHARACTER SET OCTETS</c>
///   when the Firebird client sees a System.Guid parameter.
/// - Identity columns require Firebird 3+: <c>GENERATED BY DEFAULT AS IDENTITY</c>.
/// </summary>
public class FirebirdIntegrationTests : OrmIntegrationTestBase
{
    private const string DefaultConnectionString =
        "DataSource=127.0.0.1;Port=3050;Database=/firebird/data/ormtest.fdb;"
        + "User=SYSDBA;Password=fbtest;Charset=UTF8;ServerType=0;"
        // Pooling must stay off — xUnit constructs a new test class instance
        // (and therefore a new IDbConnection) per test, but the Firebird
        // managed pool keeps prior connections warm. Those warm connections
        // hold metadata handles to widgets/gadgets/noOrder, and Firebird then
        // rejects DROP TABLE in the next test's ResetSchema with
        // "lock conflict on no wait transaction" / "object TABLE is in use".
        + "Pooling=false;";

    protected override IDbConnection CreateConnection()
    {
        var cs =
            Environment.GetEnvironmentVariable("DAWNING_ORM_FIREBIRD") ?? DefaultConnectionString;
        return new FbConnection(cs);
    }

    private void DropIfExists(string tableName)
    {
        // Firebird has no IF EXISTS; the safest form is a stored EXECUTE BLOCK
        // that swallows the "table not found" error.
        Connection.Execute(
            $@"EXECUTE BLOCK AS BEGIN
                   IF (EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = '{tableName.ToUpperInvariant()}'))
                   THEN EXECUTE STATEMENT 'DROP TABLE {tableName}';
               END"
        );
    }

    protected override void ResetSchema()
    {
        DropIfExists("widgets");
        DropIfExists("gadgets");
        DropIfExists("noOrder");
        Connection.Execute(
            @"CREATE TABLE widgets (
                Id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                Name        VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
                score_value INTEGER DEFAULT 0 NOT NULL,
                Notes       VARCHAR(255) CHARACTER SET UTF8,
                ts_ms       BIGINT NOT NULL
            )"
        );
    }

    protected override void EnsureNoOrderSchema()
    {
        DropIfExists("noOrder");
        Connection.Execute(
            @"CREATE TABLE noOrder (
                Id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                Name VARCHAR(255) CHARACTER SET UTF8 NOT NULL
            )"
        );
    }

    protected override void EnsureGadgetSchema()
    {
        DropIfExists("gadgets");
        Connection.Execute(
            @"CREATE TABLE gadgets (
                Id        CHAR(16) CHARACTER SET OCTETS NOT NULL PRIMARY KEY,
                Name      VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
                CreatedBy VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
                ServerTag VARCHAR(255) CHARACTER SET UTF8 DEFAULT 'srv-default' NOT NULL,
                Display   VARCHAR(255) CHARACTER SET UTF8
            )"
        );
    }

    protected override void DropAllTables()
    {
        DropIfExists("widgets");
        DropIfExists("gadgets");
        DropIfExists("noOrder");
    }
}
