#!/usr/bin/env pwsh
# =====================================================
# Sync Schema Script
# 将 apps/gateway/docs/sql/schema 目录下的所有 SQL 文件
# 合并到 deploy/helm/dawning/files/init.sql
# 确保 Helm 部署使用的数据与源 schema 完全一致
# =====================================================

param(
    [string]$SchemaDir = "",
    [string]$OutputFile = ""
)

$ErrorActionPreference = "Stop"

# 获取脚本所在目录
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Get-Item $ScriptDir).Parent.Parent.FullName

# 设置默认路径
if (-not $SchemaDir) {
    $SchemaDir = Join-Path $RepoRoot "apps\gateway\docs\sql\schema"
}
if (-not $OutputFile) {
    $OutputFile = Join-Path $RepoRoot "deploy\helm\dawning\files\init.sql"
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Sync Schema to Helm Init SQL" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Source: $SchemaDir" -ForegroundColor Yellow
Write-Host "Target: $OutputFile" -ForegroundColor Yellow
Write-Host ""

# 检查源目录是否存在
if (-not (Test-Path $SchemaDir)) {
    Write-Host "Error: Schema directory not found: $SchemaDir" -ForegroundColor Red
    exit 1
}

# 确保目标目录存在
$OutputDir = Split-Path -Parent $OutputFile
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    Write-Host "Created directory: $OutputDir" -ForegroundColor Green
}

# 获取所有 SQL 文件并按文件名排序
$SqlFiles = Get-ChildItem -Path $SchemaDir -Filter "*.sql" | Sort-Object Name

if ($SqlFiles.Count -eq 0) {
    Write-Host "Error: No SQL files found in $SchemaDir" -ForegroundColor Red
    exit 1
}

Write-Host "Found $($SqlFiles.Count) SQL files:" -ForegroundColor Green
$SqlFiles | ForEach-Object { Write-Host "  - $($_.Name)" -ForegroundColor Gray }
Write-Host ""

# 创建合并后的 SQL 内容
$Header = @"
-- =====================================================
-- Dawning Gateway - Database Initialization Script
-- Auto-synced from: apps/gateway/docs/sql/schema/
-- Generated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
-- 
-- DO NOT EDIT THIS FILE DIRECTLY!
-- Edit the source files in apps/gateway/docs/sql/schema/
-- Then run: deploy/scripts/sync-schema.ps1
-- =====================================================

"@

$Content = $Header

foreach ($File in $SqlFiles) {
    Write-Host "Processing: $($File.Name)..." -ForegroundColor Gray
    
    # 读取文件内容
    $FileContent = Get-Content -Path $File.FullName -Raw -Encoding UTF8
    
    # 移除 USE 语句（Helm 部署会在创建数据库后自动选择）
    $FileContent = $FileContent -replace "(?mi)^\s*USE\s+[`'\w]+\s*;\s*$", ""
    
    # 移除 DROP TABLE 语句（初始化时不需要删除表）
    $FileContent = $FileContent -replace "(?mi)^\s*DROP\s+TABLE\s+IF\s+EXISTS\s+[`'\w]+\s*;\s*$", ""
    
    # 添加文件分隔注释
    $Content += @"

-- =====================================================
-- Source: $($File.Name)
-- =====================================================
$FileContent
"@
}

# 写入目标文件
$Content | Out-File -FilePath $OutputFile -Encoding UTF8 -Force

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host " Sync completed successfully!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Output file: $OutputFile" -ForegroundColor Yellow
Write-Host "File size: $([math]::Round((Get-Item $OutputFile).Length / 1024, 2)) KB" -ForegroundColor Yellow
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review the generated file" -ForegroundColor Gray
Write-Host "  2. Run helm upgrade/install to deploy" -ForegroundColor Gray
